### ISSUE TITLE
Insert large chunks of content freezes the window for a moment

### ISSUE THREAD

**Issue by dmonad** [y-js/y-array#2]
E.g. `array.insert(0, Array(10000).map(=>{return "content"}))` - inserting 10000 elements will freeze the window for a moment.

y-text and y-richtext inherit this problem for text editing

**Comment by dennislaupman** [comment]
Would be nice if we can fix this. I Think it not necessary to split up in an array? 

var content = "Hello orld!";
var character = "w";
var position = 6;

[content.slice(0, position), character, content.slice(position)].join('');

We having big performance issues with large text right noq.

Grtz Dennis

**Comment by dmonad** [comment]
I fear it is necessary to split up characters in an array (that's just how the algorithm works). But several performance improvements are possible. I.e. Currently, characters are inserted one-by-one into the array - which causes problems when inserting larger amounts of text. Furthermore, also the characters are sent one-by-one to the other clients (which is of course imperformant). I wanted to keep the algorithm rather simple at the beginning, because there are some edge cases that you have to handle when sending larger amount of text at once. But I'm confident that I can fix this in the next two month.

**Comment by dmonad** [comment]
Fixed in Yjs@11.0.0
