### ISSUE TITLE
Large inserts throw RangeError.

### ISSUE THREAD

**Issue by t-mullen** [y-js/y-array#5]
[This line](https://github.com/y-js/y-array/blob/master/src/Array.js#L59) will throw a RangeError when contents have a length > 65535 (in Chrome), or 262143 (in Firefox).

Inserts should be chunked so that nothing longer than 65534 is given to `.apply`.

Here's how I did it externally, if you're interested. (Probably a more performant way to do it)

```javascript
function insertChunked(ytext, start, str) {
  var i = start
  var CHUNK_SIZE = 65532
  chunkString(str, CHUNK_SIZE).forEach(function (chunk) {
    ytext.insert(i, chunk)
    i+=chunk.length
  })
}

function chunkString(str, size) {
  var numChunks = Math.ceil(str.length / size),
      chunks = new Array(numChunks);

  for(var i = 0, o = 0; i < numChunks; ++i, o += size) {
    chunks[i] = str.substr(o, size);
  }

  return chunks;
}
```

**Comment by dmonad** [comment]
This is a good one.. I'm even more convinced that there is something wrong with JavaScript Arrays. I did some research and I still don't know what the "right" way to do is.. So I'm just gonna fix it in a dirty way.

**Comment by dmonad** [comment]
This is fixed in y-text@10.0.7

**Comment by marijnh** [comment]
> I'm even more convinced that there is something wrong with JavaScript Arrays

(This wasn't really about arrays—the problem is that on many engines calling `Function.apply` with a huge array will push all the values on the array onto the stack, often overflowing it. Though on the other hand, `Array.splice` is such a god-awfully bad interface that you could make a point that there's something wrong with JS arrays.)

**Comment by dmonad** [comment]
Related to this issue is a recent discussion: https://github.com/yjs/yjs/issues/191

Because of this problem, I started to completely avoid vararg functions for inserting content.
