### ISSUE TITLE
Which algorithm y-array is using?

### ISSUE THREAD

**Issue by gritzko** [y-js/y-array#9]
I assume, it is some variation of id-based CRDT? Which one?
What is the intended semantics of Y.utils.inDeletionRange?
```
function inDeletionRange (del, ins) {
    return del.target[0] === ins[0] && del.target[1] <= ins[1] && ins[1] < del.target[1] + (del.length || 1)
}
```

**Comment by nicolaescu** [comment]
Hi, Y is basically a CRDT. You can find the full description here: http://dl.acm.org/citation.cfm?id=2957310 On Aug 19, 2017 11:16 AM, Victor Grishchenko <notifications@github.com> wrote:I assume, it is some variation of id-based CRDT? Which one?
What is the intended semantics of Y.utils.inDeletionRange?
function inDeletionRange (del, ins) {
    return del.target[0] === ins[0] && del.target[1] <= ins[1] && ins[1] < del.target[1] + (del.length || 1)
}

**Comment by gritzko** [comment]
Looks RGA-ish indeed. You should probably spend more time comparing it
to RGA. It is not really clear why you decided to reinvent the thing.

Are you serious about O(H^2) insertion complexity? That is explosive.


On 19 August 2017 at 12:27, nicolaescu <notifications@github.com> wrote:
> Hi, Y is basically a CRDT. You can find the full description here:
> http://dl.acm.org/citation.cfm?id=2957310 On Aug 19, 2017 11:16 AM, Victor
> Grishchenko <notifications@github.com> wrote:I assume, it is some variation
> of id-based CRDT? Which one?
> What is the intended semantics of Y.utils.inDeletionRange?
> function inDeletionRange (del, ins) {
> return del.target[0] === ins[0] && del.target[1] <= ins[1] && ins[1] <
> del.target[1] + (del.length || 1)
> }
>
>
> —You are receiving this because you are subscribed to this thread.Reply to
> this email directly, view it on GitHub, or mute the thread.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Victor

**Comment by gritzko** [comment]
> As such, the retrieval of a specific operation can be efficiently implemented using a balanced tree, which exposes time complexities of O(log(H)) for insertion and retrieval. Here, H denotes the number of all applied operations in the balanced tree implementation.

Highly confusing wording. You can't apply H operations in O(log(H)).
No idea what you meant here.

**Comment by gritzko** [comment]
I assumed H to mean either the number of operations being inserted or the size of the document (which is a sum of all the ops applied, historically). The former makes O(log(H)) a joke, the latter makes O(H^2) a bomb.

**Comment by dmonad** [comment]
Hello @gritzko,

Let me try to clarify the wording to you. Operations represent changes on the document. Each operation has a unique id. The History is not an append-only log of all operations, but a balanced tree that maps `operation.id->operation`. The complexity of inserting / retrieving an operation is in O(log(H)), where H is the size of the balanced tree.

The actual complexity of applying an operation is in O(n^2), where n is the number of all operations that were applied by other users concurrently and at the same position. Example:

Initial document: "Text"
* User1 inserts character "A" at position 0
* User2 inserts character "B" at position 0
* User3 insert character "C" at position 0
* User4 inserts character "D" at position 4

User1 computes operations:
* User1 retrieves content from User2. Complexity to apply is O(1^2)
* User1 retrieves content from User3. Complexity to apply is O(2^2)
* User1 retrieves content from User4. Complexity to apply is O(1^2) (since change happened on a different position)

So why did we write that the time complexity is actually in O(H^2), not O(n^2)? It is a well established practice to use the size of the history to compare algorithms for their worst case behavior. In some cases `H` may actually be equal to `n`.

What the big O notation does not tell you is that this is the absolute worst case. I can assure you that the time complexity is absolutely fine in practice. Furthermore, conflicts do not happen that often and they only need to be resolved once.

The strength of Yjs is that it has a great syncing protocol and that it is possible to garbage collect operations from the history (so the memory does not blow up).

**Comment by gritzko** [comment]
Well, O(N^2) is quite a nightmare. Actually, OT has two big shortcomings: complexity and O(N^2). CRDT is supposed to fix both.
When I was much younger (a student), one friend of mine tested web servers for quadratic behavior. If found, he sent them into the outer space, just for the fun of it.

**Comment by gritzko** [comment]
I guess, my garbage collection questions are now unnecessary.

**Comment by dmonad** [comment]
I felt that your last comment was a good point to close this thread. I am happy to discuss my design decisions in more detail.

**Comment by gritzko** [comment]
Sorry for reading your paper too carefully, but I believe that the
original RGA has O(1) local insertion, not O(N). It picks an old node
in a hash table, pushes a new node into the linked list. Both are
O(1).
(I personally find that choice of data structures rather bizarre, but
formally it should be optimal)

**Comment by dmonad** [comment]
From a theoretical point of view, RGA has some really nice properties. The authors carefully designed the algorithm to have a O(1) complexity. But if you read the paper carefully, you will realize that the memory consumption is astronomical. In computer science, this phenomenon is known as a [space-time tradeoff](https://en.wikipedia.org/wiki/Space%E2%80%93time_tradeoff). My main concerns about RGA in practice are the following:

* A Node consists of `2 x s4vector + 2 x Pointer + character` (Remember: `s4vector = 4 integer`) That's 40 bytes of additional information for each character.
* It is a bad idea to manage operations in a Hash Table. It is easily possible to have a document size between 1 and 300000 characters (anything above goes obviously too). When the hash table is recreated, your computer will literally freeze when you typed more than ~10000 characters (in Javascript)
* A single operation is encoded in 62 + 8 bytes (`4 x s4vector + character`). I don't know how they implemented syncing, but I wouldn't be surprised if it involves exchanging `70B x #charcters` to all peers.
* It is theoretically possible that a local operation overwrites a remote operation. RGA only assures convergence

So this is my take on RGA.. Yjs does not share any concepts with the RGA algorithm. If you want to compare it conceptually, Yjs is actually more similar to WOOT. While both algorithms have a time complexity of O(H^2), the syncing process is actually very performant in Yjs. In WOOT, you basically have to apply all operations from the beginning of time. In Yjs only missing operations need to be applied.

You got me thinking. I could improve the complexity to O(log(n)*N) by using a lookup table. This will make Yjs look better on paper. But I doubt that this makes a difference in practice. Conflicts rarely occur in practice. Again to clarify, this is the number of characters that is inserted at the same time+same position. Have a look at [this comparison of CRDTs](https://hal.archives-ouvertes.fr/inria-00629503/document). Even when a large number of conflicts are forced, WOOT performs pretty similar to RGA, without having a big memory overhead.

**Comment by gritzko** [comment]
Now I see. They explicitly assume the worst case of all the document
being assembled at once. Then, O(1) becomes O(H).

In JS and other higher-level languages, objects have quite a lot of
overhead: headers, gc bookkeeping, etc. That may dwarf those 62+8
bytes. That's why Causal Tree (my RGAish algo) keeps the data in
strings or typed arrays.

If you have O(H^2) somewhere, some Good Samaritan will almost
certainly trigger it one day. Quite often, with some legitimate use
case. Regarding our CT editor, once we had O(N^2) behavior triggered
in the URL parsing regex (!!!) by a very long (legitimate) URL. Given
enough of users, those things happen.

Y.js is quite an interesting project. Good luck!

**Comment by dmonad** [comment]
Thanks for your feedback. I will definitely improve my algorithm using a lookup table. You are right, one should always plan for the worst case scenario.

I had a look at your paper on Causal Trees when I did my initial research. Honestly, I skipped it when I read that it uses timestamps for conflict resolution. Now I see that there is a lot of potential in Causal Trees. But I wonder how you solved garbage collection. Assuming a user writes the following document "abcd..xyz" and then deletes the first 25 characters. This should result in the following Causal Tree:

```
a (deleted)
|->b (deleted)
   |->c (deleted)
       ..->y (deleted)
           |->z
```

Are you actually able to garbage collect the letters a to y?

**Comment by gritzko** [comment]
Yes, that is possible. Unfortunately, I did not publish that yet.
Obviously, it breaks monotonic features, cause someone might have seen/referenced those missing characters, so some additional bookkeeping is needed.
For shorter texts that may not worth the hassle.

**Comment by gritzko** [comment]
P.S. CT uses logical/Lamport/hybrid timestamps. In fact, that could be 1, 2, 3.

**Comment by dmonad** [comment]
Cool. Garbage Collection was one of my major issues when I developed Yjs. I haven't yet found the ultimate gc solution yet. But at least for Client-Server architectures I am able to keep the document size in O(#characters+#users) (even with offline editing).

You have any more questions?

**Comment by gritzko** [comment]
For strictly client-server, you can always ask the client to rebase changes.
It was nice to chat with you!

**Comment by dmonad** [comment]
That's pretty much what I am doing. I rebase changes so that the structure doesn't break.
Yeah, its always nice to discuss CRDTs.
Good luck to you too!
